SELECT I.SUMMARY, I.DESCRIPTION, L.NAME
FROM ISSUES I
JOIN ISSUESLISTS L ON I.ISSUESLISTS_ID = L.ID;

SELECT I.SUMMARY, U.FIRSTNAME, U.LASTNAME
FROM ISSUES I
JOIN USERS U on I.USER_ID_ASSIGNEDTO = U.ID;

SELECT U.ID, U.FIRSTNAME, U.LASTNAME, COUNT(*) AS ISSUES_NUMBER
FROM ISSUES I
JOIN USERS U ON I.USER_ID_ASSIGNEDTO = U.ID
GROUP BY U.ID;