INSERT INTO POSTS (USER_ID, BODY)
VALUES (3, "HELLO");
INSERT INTO POSTS (USER_ID, BODY)
VALUES (1, "NEXT POST");
INSERT INTO POSTS (USER_ID, BODY)
VALUES (2, "Hi there");

COMMIT ;

SELECT * FROM POSTS;

UPDATE POSTS
SET BODY = "To delete"
WHERE ID=10 OR ID=8 OR ID = 9;

COMMIT ;

DELETE FROM POSTS
WHERE ID=10 OR ID=8 OR ID = 9;

COMMIT ;